// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCormbCwqOMAP3semfM-AtfGwTO56edkxU',
    appId: '1:747768754958:android:8ca987a0675b8c25bb5d5f',
    messagingSenderId: '747768754958',
    projectId: 'holy-land-pilgrimage-app',
    storageBucket: 'holy-land-pilgrimage-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw1St5Cpm_EBFJ22IDINZ2PK6rF1I_XKQ',
    appId: '1:747768754958:ios:6dd20f8cbb61b017bb5d5f',
    messagingSenderId: '747768754958',
    projectId: 'holy-land-pilgrimage-app',
    storageBucket: 'holy-land-pilgrimage-app.firebasestorage.app',
    androidClientId: '747768754958-4vg7gnsu7kf75brk39utdi590do3juli.apps.googleusercontent.com',
    iosClientId: '747768754958-h2ccp7rdpl24k2vd8f93r7g7a49cdo52.apps.googleusercontent.com',
    iosBundleId: 'com.example.pilgrimageApp',
  );

}